[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
{{rust-name-snake-case}} = "{{program-id}}"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"
