[template]
cargo_generate_version = ">=0.18.2"


[placeholders.rust-name]
type = "string"
prompt = "Name of the Rust crate (kebab-case)"

[placeholders.rust-name-snake-case]
type = "string"
prompt = "Name of the Rust crate (snake_case)"

[placeholders.rust-name-camel-case]
type = "string"
prompt = "Name of the Rust crate (UpperCamelCase)"

[placeholders.program-id]
type = "string"
prompt = "Solana program ID"
default = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[placeholders.anchor-version]
type = "string"
prompt = "Anchor version"

[placeholders.light-hasher-version]
type = "string"
prompt = "light hasher version"

[placeholders.stateless-js-version]
type = "string"
prompt = "stateless js version"

[placeholders.anchor-js-version]
type = "string"
prompt = "anchor js version"
