[package]
name = "{{rust-name}}"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "{{rust-name-snake-case}}"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = ["idl-build"]
test-sbf = []
idl-build = ["anchor-lang/idl-build", "light-sdk/idl-build"]

[dependencies]
anchor-lang = "{{anchor-version}}"
light-sdk = { version = "{{light-sdk-version}}", features = [
    "anchor",
    "idl-build",
] }
light-hasher = { version = "{{light-hasher-version}}", features = ["solana"] }
